### ISSUE TITLE
mongoose-q

### ISSUE THREAD

**Issue by cAstraea** [SimplyTechnologies/messenger-bot-wit-boilerplate#1]
Hello , I think this package might be long time deprecated ? 
Think can use official mongoose package since promises are handled natively now ? What do you suggest ? Thank you

**Comment by shahen94** [comment]
Hi @cAstraea.
Yes  You're right, right now mongoose have promise support from the box. Even we can use native promises. However that's not a our target to work on these days. But PR are welcome
